---
- name: add the rabbitmq official repo
  sudo: yes
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    state: present

- name: add the rabbitmq public key
  sudo: yes
  apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
    state: present

- name: update the apt cache
  sudo: yes
  apt:
    update_cache: true

- name: install rabbitmq-server
  sudo: yes
  apt:
    name: rabbitmq-server
    state: present

- name: ensure rabbitmq is running and enabled
  sudo: yes
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: enable web management for rabbit
  sudo: yes
  command: rabbitmq-plugins enable rabbitmq_management
